### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by willingc** [nteract/naming#3]

**Comment by rgbkrk** [comment]
Ohhhh, we actually use this to name the releases. The scientists.txt file should be moved into the nteract monorepo and this should be archived. I progress down the list taking the next name and an alliterative adjective (if possible) when crafting the release name.

Yesterday we released [`Blottesque Blodgett`](https://github.com/nteract/nteract/releases/tag/v0.12.1), named after physicist [Katharine Burr Blodgett](https://en.wikipedia.org/wiki/Katharine_Burr_Blodgett) known for her invention of nonreflective glass. 

![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Katharine_Burr_Blodgett_%281898-1979%29%2C_demonstrating_equipment_in_lab.jpg/500px-Katharine_Burr_Blodgett_%281898-1979%29%2C_demonstrating_equipment_in_lab.jpg)

I'm not actually sure where I found this list of scientists. It would be nice if we leaned into talking about the scientists on each release. 😄 Probably good to queue up a tweet about Dr. Blodgett.

**Comment by willingc** [comment]
Oooh. Cool. Adafruit often features scientists too so another place to look.

**Comment by willingc** [comment]
@captainsafia This sentence in wikipedia cracked me up:

> She received a star in the seventh edition of American Men of Science (1943), recognizing her as one of the 1,000 most distinguished scientists in the United States.[16]

YouTube https://www.youtube.com/watch?v=etgCq438XRk

**Comment by rgbkrk** [comment]
By the way, I called nteract in Alpha when we were in the A names and then Beta while we're in the B names. 😅 

> She received a star in the seventh edition of American Men of Science (1943), recognizing her as one of the 1,000 most distinguished scientists in the United States.[16]

Just wow.

**Comment by rgbkrk** [comment]
Now that https://github.com/nteract/nteract/pull/3516 has been merged, we can archive this repository. 🎉
